### ISSUE TITLE
Deleting Workflow does not remove created Jobs

### ISSUE THREAD

**Issue by alexei-led** [sdminonne/workflow-controller#18]
Hi, I'm not sure if this is by design, but I was expecting that when I'm deleting a completed workflow all Jobs created by this workflow will be deleted too. This is not the case. So, I manually should go and delete all Jobs using label selector.
Any plans to delete K8s resources, when the workflow is deleted? Or to create some kind of GC that cleanups resources without "parent" workflow?

**Comment by sdminonne** [comment]
@alexei-led it's a bug and I've a fix (to be honest partial) in my sandbox. 
I just need sometime to finalize the code and push it.
Final implementation will be this: deleting a workflow will remove all the (running jobs and related pods).
All the already finished jobs will be kept (and need to be removed by hands).

**Comment by alexei-led** [comment]
What is the reason to keep finished Jobs after deleting the Workflow? Usually, when you remove "parent" Kubernetes resource all its children are removed too, no matter what status is (completed, running, etc).

Maybe, it's worth to add a config/parameter to the controller, to allow to specify the desired behavior. For example `--keep-finished-jobs=true|false`?

**Comment by alexei-led** [comment]
You also may consider adding a "Garbage Collector" to clean up "orphan" resources. Something similar to `etcd-operator GC` https://github.com/coreos/etcd-operator/blob/master/pkg/garbagecollection/gc.go

**Comment by sdminonne** [comment]
@alexei-led discussed with @clamoriniere1A and finally, I agree that we should remove all the resources associated to the workflow. 
And implementing a `GC` is a good idea as well. Going to do in the next days and we will keep this issue open to track it. Thanks.
