### ISSUE TITLE
What is the status ?

### ISSUE THREAD

**Issue by chronidev** [sdminonne/workflow-controller#2]
Hi,

I just want to know the status of this controller, doesn't it planned to be integrated in kubernetes or not ? I saw that the initial design proposal was removed from kubernetes repository.

Regards,

**Comment by sdminonne** [comment]
It won't. DAG/workflow are complex objects and kubernetes community today has not enough resources to take care of additional load (code review, support, doc).

It will remain an external controller, but I'll keep to support it and work on it. 
In the next days (well, maybe weeks) I'm going to port it on kube CDR removing TPR.

**Comment by sdminonne** [comment]
Porting to CDR is on going.

**Comment by sdminonne** [comment]
see #3

**Comment by sdminonne** [comment]
going to close this. Don't hesitate to ask/re-open if you need more info.
